package model;

public enum Section {
    KARDANI,
    KARSHENASI_PEYVASTE,
    KARSHENASI_NAPEYVASTE,
    KARSHENASI_ARSHAD_PEYVASTEH,
    KARSHENASI_ARSHAD_NAPEYVASTEH,
    DOKTORAY_HERFEII,
    DOKTORAY_PEYVASTEH,
    DOKTORAY_NAPEYVASTEH
}
